// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vcfosauberwbatamhqat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZm9zYXViZXJ3YmF0YW1ocWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTI5OTIsImV4cCI6MjA3Mzc4ODk5Mn0._QJ5im3nr9IUbOmDO3Hg5fPhCIjDYxW0CLdrEVntHQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);